- hosts: all
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker Compose is installed
      shell: |
        COMPOSE_VERSION="1.29.2"
        curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      args:
        executable: /bin/bash

    - name: Copy docker-compose.yml to the server
      copy:
        src: ./docker-compose.yml
        dest: /home

    - name: Copy nginx.conf to the server
      copy:
        src: ./nginx.conf
        dest: /home
    - name: Copy HTML files to the server
      copy:
        src: ./html
        dest: /home
        mode: '0755'
        owner: www-data
        group: www-data

    - name: Start Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home